import { Complaint, StationProfile, CallCenterOfficer } from "./types";

export const STATIONS: StationProfile[] = [
  {
    name: "Rathmalana (CWS)",
    code: "Rathmalana",
    passwordHash: "rathmalana123",
    address: "No.75, Kandawala Road, Ratmalana",
    managerName: "Primal H. (Assistant Workshop Manager)",
    email: "primal.h@idealgroup.lk",
    phone: "0771053496",
    officers: [
      { name: "Primal H.", role: "Assistant Workshop Manager - Mechanical", email: "primal.h@idealgroup.lk", phone: "0771053496" }
    ]
  },
  {
    name: "Wanawasala",
    code: "Wanawasala",
    passwordHash: "wanawasala123",
    address: "No.17 & 19, Wanawasala Road, Kelaniya",
    managerName: "Akila Manoj (Manager - Workshop)",
    email: "manjula.thushara@idealgroup.lk, akila.manoj@idealgroup.lk",
    phone: "0772976110 / 0770168705",
    officers: [
      { name: "Manjula Thushara", role: "Senior Service Advisor", email: "manjula.thushara@idealgroup.lk", phone: "0772976110" },
      { name: "Akila Manoj", role: "Manager - Workshop", email: "akila.manoj@idealgroup.lk", phone: "0770168705" }
    ]
  },
  {
    name: "Yakkala",
    code: "Yakkala",
    passwordHash: "yakkala123",
    address: "No 175/C/1, Aluthgama, Bogamuwa, Yakkala",
    managerName: "Chamila Sugathadasa (Manager - Workshop)",
    email: "chamila.sugathadasa@idealgroup.lk",
    phone: "0769923360",
    officers: [
      { name: "Chamila Sugathadasa", role: "Manager – Workshop", email: "chamila.sugathadasa@idealgroup.lk", phone: "0769923360" }
    ]
  },
  {
    name: "Kurunegala",
    code: "Kurunegala",
    passwordHash: "kurunegala123",
    address: "No.167/1, Colombo Rd, Wanduragala, Kurunegala",
    managerName: "Deshan Manujaya (Service Advisor)",
    email: "anuruddha.rasanjana@idealgroup.lk, deshan.manujaya@idealgroup.lk",
    phone: "0765956437 / 0770188986",
    officers: [
      { name: "Anuruddha Rasanjana", role: "Junior Service Advisor", email: "anuruddha.rasanjana@idealgroup.lk", phone: "0765956437" },
      { name: "Deshan Manujaya", role: "Service Advisor", email: "deshan.manujaya@idealgroup.lk", phone: "0770188986" }
    ]
  },
  {
    name: "Anuradhapura",
    code: "Anuradhapura",
    passwordHash: "anuradhapura123",
    address: "No 562/K, Jayanthi Mawatha, Anuradhapura",
    managerName: "Sajith Maduranga (Assistant Manager - Workshop)",
    email: "sajith.maduranga@idealgroup.lk",
    phone: "0740887512",
    officers: [
      { name: "Sajith Maduranga", role: "Assistant Manager – Workshop", email: "sajith.maduranga@idealgroup.lk", phone: "0740887512" }
    ]
  },
  {
    name: "Jaffna",
    code: "Jaffna",
    passwordHash: "jaffna123",
    address: "No.63, Nadumkulam Rd, Ariyalai, Jaffna",
    managerName: "Komalan P. (Assistant Manager - Workshop)",
    email: "komalan.p@idealgroup.lk",
    phone: "0767245433",
    officers: [
      { name: "Komalan P.", role: "Assistant Manager – Workshop", email: "komalan.p@idealgroup.lk", phone: "0767245433" }
    ]
  },
  {
    name: "Tissamaharama",
    code: "Tissamaharama",
    passwordHash: "tissamaharama123",
    address: "No.434/A, Gangasiripura, Tissamaharama",
    managerName: "Thushara S. (Manager - Workshop)",
    email: "thushara.s@idealgroup.lk",
    phone: "0775524421",
    officers: [
      { name: "Thushara S.", role: "Manager – Workshop", email: "thushara.s@idealgroup.lk", phone: "0775524421" }
    ]
  }
];

export const CALL_CENTER_OFFICERS: CallCenterOfficer[] = [
  {
    id: "CC-101",
    name: "Usha",
    title: "Senior CX Call Center Executive",
    email: "usha@idealgroup.lk",
    phone: "+94 77 111 2233",
    avatar: "US",
    department: "Ideal Motors Central CX Call Center",
    passwordHash: "callcenter123"
  },
  {
    id: "CC-102",
    name: "Irshana",
    title: "CX Resolution Specialist",
    email: "irshana@idealgroup.lk",
    phone: "+94 77 222 3344",
    avatar: "IR",
    department: "Ideal Motors Central CX Call Center",
    passwordHash: "callcenter123"
  },
  {
    id: "CC-103",
    name: "Yathish",
    title: "Aftermarket Follow-Up Officer",
    email: "yathish@idealgroup.lk",
    phone: "+94 77 333 4455",
    avatar: "YA",
    department: "Ideal Motors Central CX Call Center",
    passwordHash: "callcenter123"
  },
  {
    id: "CC-104",
    name: "Pawani",
    title: "Customer Verification Executive",
    email: "pawani@idealgroup.lk",
    phone: "+94 77 444 5566",
    avatar: "PA",
    department: "Ideal Motors Central CX Call Center",
    passwordHash: "callcenter123"
  },
  {
    id: "CC-105",
    name: "Shevon",
    title: "Call Center Operations Lead",
    email: "shevon@idealgroup.lk",
    phone: "+94 77 555 6677",
    avatar: "SH",
    department: "Ideal Motors Central CX Call Center",
    passwordHash: "callcenter123"
  }
];


export const DEMO_COMPLAINTS: Complaint[] = [
  // ================= RATHMALANA (2 REJECTED CASES) =================
  {
    id: "COMP-RATH-01",
    woNo: "WO-10821",
    customerName: "Kamal Perera",
    customerPhone: "+94 77 123 4567",
    customerEmail: "kamal.perera@gmail.com",
    station: "Rathmalana",
    category: "Mechanical",
    description: "Suspension clunking noise over small bumps. Customer waited 4 hours but front suspension rattle was not resolved.",
    date: "2026-06-20",
    receivedDateTime: "2026-06-20 08:30 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Inspected stabilizer link rods and torqued control arm bushings. Test drive completed within workshop yard.",
    stationContactedDate: "2026-06-21",
    stationResponseRejectedDate: "2026-06-22",
    stationResponseRejectedBy: "Usha (Senior CX Call Center Executive)",
    stationResponseRejectionReason: "Call Center verified with customer: Customer confirmed suspension sound still loudly audible over 20km/h. Workshop did not replace worn stabilizer bushing.",
    callCenterFinalRemarks: "Customer dissatisfied. Returned to Rathmalana for physical re-inspection and stabilizer bushing replacement.",
    notes: "Active CC Rejection: Awaiting Rathmalana Workshop Manager urgent re-contact.",
    agentName: "Usha",
    assignedOfficerId: "CC-101",
    vehicleRegNo: "WP-CAB-4412",
    mchCodeDescription: "Mahindra KUV100",
    workType: "Running Repairs",
    advisorName: "Primal H.",
    npsScore: 2
  },
  {
    id: "COMP-RATH-02",
    woNo: "WO-10822",
    customerName: "Sanjeewa Wickramasinghe",
    customerPhone: "+94 77 981 2234",
    customerEmail: "sanjeewa.w@gmail.com",
    station: "Rathmalana",
    category: "Electrical",
    description: "Air conditioner cooling cuts off automatically after driving for 15-20 minutes. Blower blows hot air in traffic.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 09:45 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Topped up R134a refrigerant gas and cleaned condenser fins with water spray.",
    stationContactedDate: "2026-06-22",
    stationResponseRejectedDate: "2026-06-23",
    stationResponseRejectedBy: "Irshana (CX Resolution Specialist)",
    stationResponseRejectionReason: "Call Center audit check: Customer reports AC compressor trip switch still overheats. Gas top-up did not fix magnetic clutch coil electrical fault.",
    callCenterFinalRemarks: "Customer stranded in noon traffic. Returned to Rathmalana for AC compressor clutch coil testing.",
    notes: "Active CC Rejection: Requires senior auto-electrician investigation.",
    agentName: "Irshana",
    assignedOfficerId: "CC-102",
    vehicleRegNo: "WP-KV-8890",
    mchCodeDescription: "Mahindra Scorpio",
    workType: "Electrical Repairs",
    advisorName: "Primal H.",
    npsScore: 1
  },
  {
    id: "COMP-RATH-03",
    woNo: "WO-10823",
    customerName: "Dammika Senaratne",
    customerPhone: "+94 71 334 5566",
    customerEmail: "dammika.s@gmail.com",
    station: "Rathmalana",
    category: "Service Delay",
    description: "Scheduled 10,000km periodic maintenance. Delayed by 3 hours due to technician shortage.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 10:00 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    stationResponseStatus: "Submitted to Call Center",
    feedbackStatus: "Satisfied",
    finalStatus: "Resolved",
    stationResolutionNotes: "Apologized for delay. Provided complimentary car interior detailing and priority express bay slot.",
    stationContactedDate: "2026-06-24",
    callCenterContactedDate: "2026-06-25",
    callCenterFinalRemarks: "Customer confirmed high satisfaction with complimentary interior detailing.",
    notes: "Case resolved and confirmed by CC.",
    agentName: "Pawani",
    assignedOfficerId: "CC-104",
    vehicleRegNo: "WP-CAD-1029",
    mchCodeDescription: "Mahindra Bolero",
    workType: "Periodic Maintenance",
    advisorName: "Primal H.",
    npsScore: 8
  },

  // ================= YAKKALA (4 REJECTED CASES) =================
  {
    id: "COMP-YAK-01",
    woNo: "WO-10901",
    customerName: "Dilini Senanayake",
    customerPhone: "+94 72 456 7890",
    customerEmail: "dilini.sena@outlook.com",
    station: "Yakkala",
    category: "Billing Dispute",
    description: "Brake pad replacement estimated at LKR 18,000 but charged LKR 32,000 without prior authorization. Severe steering shudder during braking.",
    date: "2026-06-19",
    receivedDateTime: "2026-06-19 11:45 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Explained billing breakdown to customer over phone. Offered 5% labor discount on next service.",
    stationContactedDate: "2026-06-21",
    stationResponseRejectedDate: "2026-06-22",
    stationResponseRejectedBy: "Yathish (Aftermarket Follow-Up Officer)",
    stationResponseRejectionReason: "Call Center audit check: Customer refused 5% token discount. Front brake disc run-out was not skimmed properly, causing severe high-speed shudder.",
    callCenterFinalRemarks: "Rejected: Station must credit unauthorized charges and skim brake rotors on warranty.",
    notes: "Active CC Rejection: Awaiting Chamila Sugathadasa workshop resolution.",
    agentName: "Yathish",
    assignedOfficerId: "CC-103",
    vehicleRegNo: "WP-CBA-9021",
    mchCodeDescription: "Mahindra XUV300",
    workType: "Brake System Repair",
    advisorName: "Chamila Sugathadasa",
    npsScore: 1
  },
  {
    id: "COMP-YAK-02",
    woNo: "WO-10902",
    customerName: "Harsha Gunasekara",
    customerPhone: "+94 77 444 8811",
    customerEmail: "harsha.g@gmail.com",
    station: "Yakkala",
    category: "Mechanical",
    description: "Clutch pedal extremely stiff and sticking midway. Hard to engage 1st and reverse gears in morning.",
    date: "2026-06-20",
    receivedDateTime: "2026-06-20 02:15 PM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Lubricated clutch release fork pivot and pedal bushing assembly.",
    stationContactedDate: "2026-06-22",
    stationResponseRejectedDate: "2026-06-23",
    stationResponseRejectedBy: "Usha (Senior CX Call Center Executive)",
    stationResponseRejectionReason: "Call Center customer verification: Customer stated clutch master cylinder is leaking internal seals. Lubricating external fork did not fix hydraulic slippage.",
    callCenterFinalRemarks: "Rejected: Requires clutch hydraulic master cylinder inspection and replacement under warranty.",
    notes: "Active CC Rejection: Returned to Yakkala workshop.",
    agentName: "Usha",
    assignedOfficerId: "CC-101",
    vehicleRegNo: "WP-HN-3301",
    mchCodeDescription: "Mahindra Bolero Maxi Truck",
    workType: "Clutch Overhaul",
    advisorName: "Chamila Sugathadasa",
    npsScore: 2
  },
  {
    id: "COMP-YAK-03",
    woNo: "WO-10903",
    customerName: "Roshan Alwis",
    customerPhone: "+94 71 889 1234",
    customerEmail: "roshan.alwis@yahoo.com",
    station: "Yakkala",
    category: "Quality of Work",
    description: "Fresh engine oil leak dripping onto garage floor immediately after lube service.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 04:00 PM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Cleaned under-engine guard with degreaser. Claimed residue was spilled oil during drain.",
    stationContactedDate: "2026-06-22",
    stationResponseRejectedDate: "2026-06-23",
    stationResponseRejectedBy: "Shevon (Call Center Operations Lead)",
    stationResponseRejectionReason: "Call Center follow-up: Customer sent photo showing oil drain plug crush washer missing and actively dripping 100ml/night.",
    callCenterFinalRemarks: "Rejected: Urgent oil drain plug washer replacement and engine oil top-up required before engine damage occurs.",
    notes: "Active CC Rejection: High risk engine leak.",
    agentName: "Shevon",
    assignedOfficerId: "CC-105",
    vehicleRegNo: "WP-CAC-7762",
    mchCodeDescription: "Mahindra Scorpio S10",
    workType: "Lube Service",
    advisorName: "Chamila Sugathadasa",
    npsScore: 1
  },
  {
    id: "COMP-YAK-04",
    woNo: "WO-10904",
    customerName: "Kavinda Jayasuriya",
    customerPhone: "+94 76 555 7890",
    customerEmail: "kavinda.j@gmail.com",
    station: "Yakkala",
    category: "Mechanical",
    description: "Heavy black smoke and sluggish pickup when accelerating uphill. Requested injector diagnosis.",
    date: "2026-06-22",
    receivedDateTime: "2026-06-22 09:10 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Blew compressed air through engine air intake filter element.",
    stationContactedDate: "2026-06-23",
    stationResponseRejectedDate: "2026-06-24",
    stationResponseRejectedBy: "Pawani (Customer Verification Executive)",
    stationResponseRejectionReason: "Call Center check: Customer reports black smoke persists. CRDi common rail injector diagnostic scan was never carried out.",
    callCenterFinalRemarks: "Rejected: Station must connect diagnostic scanner and test fuel injector flow rates.",
    notes: "Active CC Rejection: Awaiting CRDi scanner diagnostic report from Yakkala.",
    agentName: "Pawani",
    assignedOfficerId: "CC-104",
    vehicleRegNo: "WP-LH-5519",
    mchCodeDescription: "Mahindra Bolero Camper",
    workType: "Engine Diagnosis",
    advisorName: "Chamila Sugathadasa",
    npsScore: 2
  },
  {
    id: "COMP-YAK-05",
    woNo: "WO-10905",
    customerName: "Thilak Ranasinghe",
    customerPhone: "+94 77 662 3344",
    customerEmail: "thilak.r@gmail.com",
    station: "Yakkala",
    category: "Service Delay",
    description: "Periodic 40,000km service completed. Minor delay in billing counter.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 01:30 PM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    stationResponseStatus: "Submitted to Call Center",
    feedbackStatus: "Satisfied",
    finalStatus: "Resolved",
    stationResolutionNotes: "Addressed billing queue delays and provided express invoice checkout.",
    stationContactedDate: "2026-06-24",
    callCenterContactedDate: "2026-06-25",
    callCenterFinalRemarks: "Customer satisfied with resolution.",
    notes: "Resolved.",
    agentName: "Irshana",
    assignedOfficerId: "CC-102",
    vehicleRegNo: "WP-CAF-8812",
    mchCodeDescription: "Mahindra KUV100",
    workType: "Periodic Maintenance",
    advisorName: "Chamila Sugathadasa",
    npsScore: 8
  },

  // ================= JAFFNA (2 REJECTED CASES) =================
  {
    id: "COMP-JAF-01",
    woNo: "WO-10951",
    customerName: "Muthu Ramanathan",
    customerPhone: "+94 75 555 6666",
    customerEmail: "muthu.ram@hotmail.com",
    station: "Jaffna",
    category: "Quality of Work",
    description: "Steering pulls sharply to the left on highway. Grease and stain marks left on beige leather driver seat.",
    date: "2026-06-20",
    receivedDateTime: "2026-06-20 10:10 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Performed computerized front wheel alignment and adjusted tie rod end.",
    stationContactedDate: "2026-06-22",
    stationResponseRejectedDate: "2026-06-23",
    stationResponseRejectedBy: "Usha (Senior CX Call Center Executive)",
    stationResponseRejectionReason: "Call Center follow-up: Customer confirms alignment pull is still severe and greasy seat stains were not cleaned by the station.",
    callCenterFinalRemarks: "Rejected: Jaffna station must clean interior seat stains professionally and inspect front camber/caster.",
    notes: "Active CC Rejection: Awaiting Komalan P. workshop intervention.",
    agentName: "Usha",
    assignedOfficerId: "CC-101",
    vehicleRegNo: "NP-CAA-1182",
    mchCodeDescription: "Mahindra Scorpio",
    workType: "Wheel Alignment & Wash",
    advisorName: "Komalan P.",
    npsScore: 1
  },
  {
    id: "COMP-JAF-02",
    woNo: "WO-10952",
    customerName: "Kandiah Sivakumar",
    customerPhone: "+94 77 889 9001",
    customerEmail: "sivakumar.k@gmail.com",
    station: "Jaffna",
    category: "Mechanical",
    description: "Reverse gear grinding loudly and difficult to engage when engine is warm.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 03:20 PM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Topped up 80W-90 manual transmission gear oil level.",
    stationContactedDate: "2026-06-22",
    stationResponseRejectedDate: "2026-06-23",
    stationResponseRejectedBy: "Irshana (CX Resolution Specialist)",
    stationResponseRejectionReason: "Call Center audit: Customer states reverse synchro teeth grinding is unchanged. Gear oil top-up did not fix selector linkage bushing wear.",
    callCenterFinalRemarks: "Rejected: Gear shifter linkage and reverse synchronizer sleeve must be inspected.",
    notes: "Active CC Rejection: Returned to Jaffna station.",
    agentName: "Irshana",
    assignedOfficerId: "CC-102",
    vehicleRegNo: "NP-ND-4450",
    mchCodeDescription: "Mahindra Bolero City Pickup",
    workType: "Transmission Repair",
    advisorName: "Komalan P.",
    npsScore: 2
  },

  // ================= TISSAMAHARAMA (1 REJECTED CASE) =================
  {
    id: "COMP-TIS-01",
    woNo: "WO-10981",
    customerName: "Ranjith Fernando",
    customerPhone: "+94 76 333 4444",
    customerEmail: "ranjith.f@gmail.com",
    station: "Tissamaharama",
    category: "Staff Behavior & Quality",
    description: "Starter motor hesitation during morning cold start. Service advisor was dismissive and impolite when customer explained issue.",
    date: "2026-06-20",
    receivedDateTime: "2026-06-20 02:20 PM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    stationResponseStatus: "Rejected by Call Center",
    feedbackStatus: "Returned to Service Station",
    finalStatus: "Pending with Aftermarket (Re-contact Required)",
    stationResolutionNotes: "Cleaned battery post terminals and tightened negative earth cable bolt.",
    stationContactedDate: "2026-06-21",
    stationResponseRejectedDate: "2026-06-22",
    stationResponseRejectedBy: "Yathish (Aftermarket Follow-Up Officer)",
    stationResponseRejectionReason: "Call Center customer verification: Customer vehicle failed to start completely next morning. Battery health load test showed bad cell requiring battery replacement under warranty.",
    callCenterFinalRemarks: "Rejected: Station Manager Thushara must arrange battery warranty replacement and formally apologize for advisor behavior.",
    notes: "Active CC Rejection: Awaiting battery replacement at Tissamaharama.",
    agentName: "Yathish",
    assignedOfficerId: "CC-103",
    vehicleRegNo: "SP-CAE-5510",
    mchCodeDescription: "Mahindra Bolero Maxi Truck Plus",
    workType: "Electrical Starting Issue",
    advisorName: "Thushara S.",
    npsScore: 1
  },

  // ================= WANAWASALA (ACTIVE PENDING & RESOLVED) =================
  {
    id: "COMP-WAN-01",
    woNo: "WO-10851",
    customerName: "Anura de Silva",
    customerPhone: "+94 71 987 6543",
    customerEmail: "anura.desilva@yahoo.com",
    station: "Wanawasala",
    category: "Quality of Work",
    description: "Paid over LKR 45,000 for a full engine tune-up because of an engine rattle noise. After driving out, the noise is still noticeable.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 09:15 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Dissatisfied",
    status: "Pending",
    serviceStationContactStatus: "CONTACT_ATTEMPTED",
    notes: "Station attempted contact; senior mechanic assigned for re-inspection scheduling.",
    agentName: "Pawani",
    assignedOfficerId: "CC-104",
    vehicleRegNo: "WP-CAD-8819",
    mchCodeDescription: "Mahindra Scorpio S11",
    workType: "Engine Overhaul",
    advisorName: "Manjula Thushara",
    npsScore: 3
  },
  {
    id: "COMP-WAN-02",
    woNo: "WO-10852",
    customerName: "Chathura Wickramaratne",
    customerPhone: "+94 77 331 4455",
    customerEmail: "chathura.w@gmail.com",
    station: "Wanawasala",
    category: "Service Delay",
    description: "Routine 5,000km oil and filter service completed efficiently.",
    date: "2026-06-22",
    receivedDateTime: "2026-06-22 10:30 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    stationResponseStatus: "Submitted to Call Center",
    feedbackStatus: "Satisfied",
    finalStatus: "Resolved",
    stationResolutionNotes: "Explained bill and completed full vehicle wash.",
    stationContactedDate: "2026-06-23",
    callCenterContactedDate: "2026-06-24",
    callCenterFinalRemarks: "Customer satisfied with service.",
    notes: "Resolved.",
    agentName: "Pawani",
    assignedOfficerId: "CC-104",
    vehicleRegNo: "WP-CBF-2010",
    mchCodeDescription: "Mahindra KUV100",
    workType: "Periodic Maintenance",
    advisorName: "Akila Manoj",
    npsScore: 9
  },

  // ================= KURUNEGALA (RESOLVED & PENDING) =================
  {
    id: "COMP-KUR-01",
    woNo: "WO-10881",
    customerName: "Sahan Gunawardena",
    customerPhone: "+94 77 777 8888",
    customerEmail: "sahan.guna@idealgroup.lk",
    station: "Kurunegala",
    category: "Quality of Work",
    description: "AC blower was blowing warm air after body wash. Discovered loose compressor wire switch.",
    date: "2026-06-18",
    receivedDateTime: "2026-06-18 04:05 PM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    stationResponseStatus: "Submitted to Call Center",
    feedbackStatus: "Satisfied",
    finalStatus: "Resolved",
    stationResolutionNotes: "Reconnected compressor switch wire immediately, tested cooling levels, and offered complimentary car wax voucher.",
    stationContactedDate: "2026-06-19",
    callCenterContactedDate: "2026-06-20",
    callCenterFinalRemarks: "Customer very satisfied with immediate turnaround.",
    notes: "Case closed successfully.",
    agentName: "Shevon",
    assignedOfficerId: "CC-105",
    vehicleRegNo: "NW-WP-4421",
    mchCodeDescription: "Mahindra XUV500",
    workType: "Electrical & AC",
    advisorName: "Deshan Manujaya",
    npsScore: 9
  },
  {
    id: "COMP-KUR-02",
    woNo: "WO-10882",
    customerName: "Ruwan Wijesinghe",
    customerPhone: "+94 71 223 9988",
    customerEmail: "ruwan.wije@gmail.com",
    station: "Kurunegala",
    category: "Service Delay",
    description: "Waiting for clutch pressure plate parts delivery from central warehouse.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 11:00 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Dissatisfied",
    status: "Pending",
    notes: "Station waiting for central warehouse courier.",
    agentName: "Shevon",
    assignedOfficerId: "CC-105",
    vehicleRegNo: "NW-CA-9932",
    mchCodeDescription: "Mahindra Bolero",
    workType: "Running Repairs",
    advisorName: "Anuruddha Rasanjana",
    npsScore: 3
  },

  // ================= ANURADHAPURA (PENDING & RESOLVED) =================
  {
    id: "COMP-ANU-01",
    woNo: "WO-10921",
    customerName: "Sunil Shantha",
    customerPhone: "+94 71 555 4321",
    customerEmail: "sunil.sh@outlook.com",
    station: "Anuradhapura",
    category: "Service Delay",
    description: "Scheduled tractor service at 9:00 AM, waited until parts arrived from branch.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 09:00 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Dissatisfied",
    status: "Pending",
    notes: "New complaint awaiting station advisor contact.",
    agentName: "Yathish",
    assignedOfficerId: "CC-103",
    vehicleRegNo: "NC-TR-1190",
    mchCodeDescription: "Mahindra 575 DI Tractor",
    workType: "Tractor Service",
    advisorName: "Sajith Maduranga",
    npsScore: 4
  },
  {
    id: "COMP-ANU-02",
    woNo: "WO-10922",
    customerName: "Bandara Jayasundara",
    customerPhone: "+94 77 112 3399",
    customerEmail: "bandara.j@gmail.com",
    station: "Anuradhapura",
    category: "Quality of Work",
    description: "Hydraulic lift arm valve seal leak fixed with genuine Mahindra seal kit.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 02:00 PM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    stationResponseStatus: "Submitted to Call Center",
    feedbackStatus: "Satisfied",
    finalStatus: "Resolved",
    stationResolutionNotes: "Installed new hydraulic seals and tested 1.5 ton lifting pressure.",
    stationContactedDate: "2026-06-22",
    callCenterContactedDate: "2026-06-23",
    callCenterFinalRemarks: "Customer confirmed hydraulic lift working at 100% capacity.",
    notes: "Resolved.",
    agentName: "Yathish",
    assignedOfficerId: "CC-103",
    vehicleRegNo: "NC-TR-2244",
    mchCodeDescription: "Mahindra 475 DI Tractor",
    workType: "Hydraulics",
    advisorName: "Sajith Maduranga",
    npsScore: 10
  }
];
