import { Complaint, StationProfile } from "./types";

export const STATIONS: StationProfile[] = [
  { name: "Rathmalana (CWS)", code: "Rathmalana", passwordHash: "rathmalana123" },
  { name: "Wanawasala", code: "Wanawasala", passwordHash: "wanawasala123" },
  { name: "Yakkala", code: "Yakkala", passwordHash: "yakkala123" },
  { name: "Kurunegala", code: "Kurunegala", passwordHash: "kurunegala123" },
  { name: "Anuradhapura", code: "Anuradhapura", passwordHash: "anuradhapura123" },
  { name: "Jaffna", code: "Jaffna", passwordHash: "jaffna123" },
  { name: "Tissamaharama", code: "Tissamaharama", passwordHash: "tissamaharama123" }
];

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: "COMP-101",
    customerName: "Kamal Perera",
    customerPhone: "+94 77 123 4567",
    customerEmail: "kamal.perera@gmail.com",
    station: "Rathmalana",
    category: "Service Delay",
    description: "Brought my vehicle in for regular 10,000 km maintenance at 8:30 AM. I was promised that it would be ready by 11:30 AM. However, I was made to wait in the lounge until 3:00 PM without any update or explanation. This delayed all my afternoon business appointments. Extremely unprofessional timing.",
    date: "2026-06-20",
    receivedDateTime: "2026-06-20 08:30 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    notes: "",
    agentName: ""
  },
  {
    id: "COMP-102",
    customerName: "Anura de Silva",
    customerPhone: "+94 71 987 6543",
    customerEmail: "anura.desilva@yahoo.com",
    station: "Wanawasala",
    category: "Quality of Work",
    description: "Paid over LKR 45,000 for a full engine tune-up because of an engine rattle noise. After driving out of the service station, the rattle noise is still exactly the same. It feels like the technicians didn't even look at the engine or diagnose the issue properly. I paid for nothing.",
    date: "2026-06-21",
    receivedDateTime: "2026-06-21 09:15 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Dissatisfied",
    status: "In Progress",
    notes: "Assigned vehicle check to senior mechanic. Contacted customer to arrange a re-inspection date.",
    agentName: "Nishantha Fernando"
  },
  {
    id: "COMP-103",
    customerName: "Dilini Senanayake",
    customerPhone: "+94 72 456 7890",
    customerEmail: "dilini.sena@outlook.com",
    station: "Yakkala",
    category: "Billing Dispute",
    description: "I was given an initial estimate of LKR 18,000 for brake pad replacement. When checking out, the bill was LKR 32,000! They claimed they had to change additional clips and pins without calling me to obtain prior approval. This is dishonest pricing.",
    date: "2026-06-22",
    receivedDateTime: "2026-06-22 11:45 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    notes: "",
    agentName: ""
  },
  {
    id: "COMP-104",
    customerName: "Ranjith Fernando",
    customerPhone: "+94 76 333 4444",
    customerEmail: "ranjith.f@gmail.com",
    station: "Tissamaharama",
    category: "Staff Behavior",
    description: "The service adviser at Tissamaharama station was extremely impolite. When I tried to explain the steering vibration issue, he cut me off and said 'we know what to do' in a very rude tone. Throughout my visit, he was unwelcoming and didn't greet or explain anything.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 02:20 PM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Neutral",
    status: "Contacted",
    notes: "Called Mr. Ranjith. Apologized on behalf of the station management. Informed him we are conducting internal customer care training for the Tissamaharama advisor team.",
    agentName: "Priyantha Bandara"
  },
  {
    id: "COMP-105",
    customerName: "Muthu Ramanathan",
    customerPhone: "+94 75 555 6666",
    customerEmail: "muthu.ram@hotmail.com",
    station: "Jaffna",
    category: "Vehicle Damage/Dirt",
    description: "I received my car back after body washing, and there were greasy black stains all over the beige leather driver seat and the steering wheel cover. It shows the mechanics didn't use seat protectors. My car interior was pristine before this.",
    date: "2026-06-24",
    receivedDateTime: "2026-06-24 10:10 AM",
    initialSatisfaction: "Very Dissatisfied",
    currentSatisfaction: "Very Dissatisfied",
    status: "Pending",
    notes: "",
    agentName: ""
  },
  {
    id: "COMP-106",
    customerName: "Sahan Gunawardena",
    customerPhone: "+94 77 777 8888",
    customerEmail: "sahan.guna@idealgroup.lk",
    station: "Kurunegala",
    category: "Quality of Work",
    description: "The air conditioning was cooling perfectly fine before servicing. However, after the general body wash and interior vacuum, the AC is blowing warm air only. I suspect something was damaged or disconnected during the vacuum process.",
    date: "2026-06-18",
    receivedDateTime: "2026-06-18 04:05 PM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Satisfied",
    status: "Resolved",
    notes: "Discovered that the AC compressor switch wire had come loose during interior cleaning. Reconnected the wire immediately, tested cooling levels, and offered a free car wax voucher. Customer was very happy with the quick response.",
    agentName: "Mahela Jayasundara"
  },
  {
    id: "COMP-107",
    customerName: "Sunil Shantha",
    customerPhone: "+94 71 555 4321",
    customerEmail: "sunil.sh@outlook.com",
    station: "Anuradhapura",
    category: "Service Delay",
    description: "Scheduled my tractor service for 9:00 AM, but was informed they ran out of oil filters. Had to wait for parts to arrive from another branch. Left at 4:30 PM. Complete waste of my farming day.",
    date: "2026-06-23",
    receivedDateTime: "2026-06-23 09:00 AM",
    initialSatisfaction: "Dissatisfied",
    currentSatisfaction: "Dissatisfied",
    status: "Pending",
    notes: "",
    agentName: ""
  }
];
